---
title: "P1"
author: "Pamela Trantham"
date: "May 24, 2016"
output: html_document
---

```{r}


#First plot function...only plots item parameters by class
Item.par.plot <- function(x, ...){
  nc<-nc<- length(x$LatentClass)
  plottemp <- sapply(x$LatentClass, function(x) x$item.par$delta.i)
  matplot(plottemp, type = "o", main = "Item Parameters by Class", xlab = "Items", ylab = "Parameters", pch = 20, bg = 1:nc)
    abline(h = 0, lty = 2)
    par(mfrow = c(1, 2))
    legend("topright", legend = paste("class", 1:nc, sep = " "), fill = 1:nc, col=1:nc)  
}

load("/Users/pamela/Desktop/EDPS 845/edps-845/Project/threeclass-ex.rda")
#Plot 3 class example model
Item.par.plot(threeclass_ex)

#Plot 4 class example model
Item.par.plot(threeclass_ex)



#Function to obtain average ability levels by class 
avg.theta<- function(x){
  nc<- length(x$LatentClass)
  outtheta <- sapply(x$LatentClass, function(x) mean(x$person.par$theta))
  return(outtheta)
}

#Obtain average ability levels by class - 3 class model
avg.theta(threeclass_ex)

#Obtain average ability levels by class - 4 class model
avg.theta(fourclass_ex)

```


```{r}

```


